import { Dict } from "./dictionary";
import DA from "../data/DA.json";
import DB from "../data/DB.json";
import DC from "../data/DC.json";
import DD from "../data/DD.json";
import DE from "../data/DE.json";
import DF from "../data/DF.json";
import DG from "../data/DG.json";
import DH from "../data/DH.json";
import DI from "../data/DI.json";
import DJ from "../data/DJ.json";
import DK from "../data/DK.json";
import DL from "../data/DL.json";
import DM from "../data/DM.json";
import DN from "../data/DN.json";
import DO from "../data/DO.json";
import DP from "../data/DP.json";
import DQ from "../data/DQ.json";
import DR from "../data/DR.json";
import DS from "../data/DS.json";
import DT from "../data/DT.json";
import DU from "../data/DU.json";
import DV from "../data/DV.json";
import DW from "../data/DW.json";
import DX from "../data/DX.json";
import DY from "../data/DY.json";
import DZ from "../data/DZ.json";

let dictData: Dict = {};
dictData = Object.assign(dictData, DA);
dictData = Object.assign(dictData, DB);
dictData = Object.assign(dictData, DC);
dictData = Object.assign(dictData, DD);
dictData = Object.assign(dictData, DE);
dictData = Object.assign(dictData, DF);
dictData = Object.assign(dictData, DG);
dictData = Object.assign(dictData, DH);
dictData = Object.assign(dictData, DI);
dictData = Object.assign(dictData, DJ);
dictData = Object.assign(dictData, DK);
dictData = Object.assign(dictData, DL);
dictData = Object.assign(dictData, DM);
dictData = Object.assign(dictData, DN);
dictData = Object.assign(dictData, DO);
dictData = Object.assign(dictData, DP);
dictData = Object.assign(dictData, DQ);
dictData = Object.assign(dictData, DR);
dictData = Object.assign(dictData, DS);
dictData = Object.assign(dictData, DT);
dictData = Object.assign(dictData, DU);
dictData = Object.assign(dictData, DV);
dictData = Object.assign(dictData, DW);
dictData = Object.assign(dictData, DX);
dictData = Object.assign(dictData, DY);
dictData = Object.assign(dictData, DZ);

export default dictData;
